<!--
Copyright (c) 2025 Martin Bartos
Licensed under the MIT License. See LICENSE file for details.
-->

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Fonts\*"/>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <!-- Versions -->
    <PropertyGroup>
        <AvaloniaVersion>12.1.1</AvaloniaVersion>
        <DotNetVersion>10.0.11</DotNetVersion>
    </PropertyGroup>

    <ItemGroup>

        <!-- Avalonia packages -->
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3"/>

        <!-- .NET packages -->
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(DotNetVersion)"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="$(DotNetVersion)"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(DotNetVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <!-- Other packages -->
        <PackageReference Include="SQLite3MC.PCLRaw.bundle" Version="2.4.0"/>
        <PackageReference Include="Devlooped.CredentialManager" Version="2.7.0"/>

    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Assets\Localization\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="easpace.Tests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

</Project>
