<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Fonts\*" />
        <Folder Include="Assets\Svgs\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <!-- Versions -->
    <PropertyGroup>
        <AvaloniaVersion>12.0.5</AvaloniaVersion>
        <DotNetVersion>10.0.9</DotNetVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- Avalonia packages -->
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.13" />
        
        <!-- .NET packages -->
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(DotNetVersion)" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Assets\Localization\Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Controls\MoodEntry.axaml.cs">
        <DependentUpon>MoodEntry.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Controls\JournalEntry.axaml.cs">
        <DependentUpon>JournalEntry.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
