// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using easpace.Desktop.Data;

#nullable disable

namespace easpace.Desktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);

                    b.HasDiscriminator<string>("ActivityType").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityDataEntries", (string)null);

                    b.HasDiscriminator<string>("EntryType").HasValue("ActivityDataEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Journal.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12800)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("easpace.Desktop.Features.Mood.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MoodEntries", (string)null);
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCycleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WellnessExercises", (string)null);
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessExerciseInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BreathingPhase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "Order");

                    b.ToTable("WellnessExerciseInstructions", (string)null);
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessSessionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CycleCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WellnessSessionEntries", (string)null);
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.NumericActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.Activity");

                    b.Property<double?>("Target")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("NumericActivity");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.RoutineActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.Activity");

                    b.HasDiscriminator().HasValue("Routine");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.NumericActivityDataEntry", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Numeric");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.RoutineActivityDataEntry", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Routine");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.MilestoneActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.NumericActivity");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Milestone");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.TrendActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.NumericActivity");

                    b.Property<int>("Aggregation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasDiscriminator().HasValue("Trend");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry", b =>
                {
                    b.HasOne("easpace.Desktop.Features.Activities.Entities.Activity", null)
                        .WithMany("Entries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessExerciseInstruction", b =>
                {
                    b.HasOne("easpace.Desktop.Features.Wellness.Entities.WellnessExercise", null)
                        .WithMany("Instructions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessSessionEntry", b =>
                {
                    b.HasOne("easpace.Desktop.Features.Wellness.Entities.WellnessExercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.Activity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessExercise", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
