// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using easpace.Desktop.Data;

#nullable disable

namespace easpace.Desktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasDiscriminator<string>("ActivityType").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityDataEntries");

                    b.HasDiscriminator<string>("EntryType").HasValue("ActivityDataEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Journal.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Mood.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MoodEntries");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.BreathingPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BreathingTechniqueId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BreathingTechniqueId");

                    b.ToTable("BreathingPhases");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.BreathingTechnique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cycles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BreathingTechniques");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessSessionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActualDuration")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BreathingTechniqueId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TargetDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BreathingTechniqueId");

                    b.ToTable("WellnessSessionEntries");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.MilestoneActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.Activity");

                    b.Property<double?>("Target")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Milestone");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.RoutineActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.Activity");

                    b.HasDiscriminator().HasValue("Routine");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.TrendActivity", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.Activity");

                    b.Property<double?>("Target")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Trend");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.NumericActivityDataEntry", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Numeric");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.RoutineActivityDataEntry", b =>
                {
                    b.HasBaseType("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Routine");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.DataEntries.ActivityDataEntry", b =>
                {
                    b.HasOne("easpace.Desktop.Features.Activities.Entities.Activity", null)
                        .WithMany("Entries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.BreathingPhase", b =>
                {
                    b.HasOne("easpace.Desktop.Features.Wellness.Entities.BreathingTechnique", null)
                        .WithMany("Phases")
                        .HasForeignKey("BreathingTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.WellnessSessionEntry", b =>
                {
                    b.HasOne("easpace.Desktop.Features.Wellness.Entities.BreathingTechnique", "BreathingTechnique")
                        .WithMany()
                        .HasForeignKey("BreathingTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BreathingTechnique");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Activities.Entities.Activity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("easpace.Desktop.Features.Wellness.Entities.BreathingTechnique", b =>
                {
                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
